# Generated by Django 6.0 on 2026-01-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fx', '0001_initial'),
        ('inventory', '0002_inventorybalance_inventorylot'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_margin_rate', models.DecimalField(decimal_places=4, default=0.2, max_digits=6)),
                ('supplier_markup_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=6)),
                ('rounding_unit_php', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('transport_mode', models.CharField(choices=[('OCEAN', 'Ocean'), ('AIR', 'Air')], default='OCEAN', max_length=10)),
                ('transport_krw_per_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fx_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fx.fxrateperiod')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_units', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('supplier_cost_krw_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('billable_weight_kg_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('other_cost_php_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fx_rate_snapshot', models.DecimalField(decimal_places=6, max_digits=12)),
                ('supplier_pay_php_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('transport_php_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transport_php_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('base_price_php_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('final_price_php_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.quotebatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
