# Generated by Django 6.0.1 on 2026-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_quoteline_base_price_php_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='manual_price_php_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual override price per unit (PHP). If set, this becomes final price.', max_digits=12, null=True),
        ),
    ]
