# Generated by Django 6.0.1 on 2026-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_quoteline_manual_price_php_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebatch',
            name='transport_krw_per_kg',
        ),
        migrations.RemoveField(
            model_name='quotebatch',
            name='transport_mode',
        ),
        migrations.AddField(
            model_name='quotebatch',
            name='air_krw_per_kg',
            field=models.DecimalField(decimal_places=2, default=14000, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotebatch',
            name='ocean_krw_per_kg',
            field=models.DecimalField(decimal_places=2, default=2200, max_digits=14),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('OCEAN', 'Ocean'), ('AIR', 'Air')], help_text='Optional override. If blank, uses product default transport mode.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotebatch',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='manual_price_php_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjusted price per unit (PHP). If set, this becomes final price.', max_digits=12, null=True),
        ),
    ]
