# Generated by Django 6.0 on 2026-01-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ko', models.CharField(blank=True, max_length=120)),
                ('base_unit', models.CharField(max_length=30)),
                ('net_weight_kg_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('packaging_note', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sku_code'],
            },
        ),
    ]
