# Generated by Django 6.0 on 2026-01-05 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty_units', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('avg_cost_php_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('qty_units_received', models.DecimalField(decimal_places=4, max_digits=14)),
                ('qty_units_remaining', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fx_rate_snapshot', models.DecimalField(decimal_places=6, max_digits=12)),
                ('supplier_cost_krw_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplier_markup_rate_snapshot', models.DecimalField(decimal_places=4, default=0.05, max_digits=6)),
                ('transport_mode', models.CharField(choices=[('OCEAN', 'Ocean'), ('AIR', 'Air')], max_length=10)),
                ('transport_krw_per_kg_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('billable_weight_kg_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('other_cost_php_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_cost_php_total_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('landed_cost_php_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('landed_cost_php_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
    ]
