# Generated by Django 6.0.1 on 2026-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorybalance_inventorylot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, help_text='Country of origin (ISO code, e.g. KR, NO, CL)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_name',
            field=models.CharField(blank=True, help_text='Origin name (e.g. Korea, Norway, Chile)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight_kg_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
