# Generated by Django 6.0.1 on 2026-01-10 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_origin_country_product_origin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJ', 'ADJ')], max_length=3)),
                ('qty_units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ref_table', models.CharField(blank=True, default='', max_length=50)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
