# Generated by Django 6.0.1 on 2026-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_transport_mode',
            field=models.CharField(choices=[('OCEAN', 'Ocean'), ('AIR', 'Air')], default='OCEAN', help_text='99% 고정인 기본 입고 루트 (AIR/OCEAN).', max_length=10),
        ),
    ]
