# Generated by Django 6.0.1 on 2026-01-10 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
        ('partners', '0001_initial'),
        ('pricing', '0003_quoteline_manual_price_php_per_unit'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleline',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleline',
            name='product',
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ISSUED', 'ISSUED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=12)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='partners.partner')),
                ('quote_batch', models.ForeignKey(blank=True, help_text='자동 제안가를 뽑을 견적 배치(선택).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='pricing.quotebatch')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('suggested_unit_price_php', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('manual_unit_price_php', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('final_unit_price_php', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleLine',
        ),
    ]
