# Generated by Django 6.0.1 on 2026-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_saleline_sale_remove_saleline_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_channel',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('ONLINE', 'Online'), ('AGENT', 'Agent'), ('OTHER', 'Other')], default='DIRECT', help_text='판매 출처(채널).', max_length=20),
        ),
    ]
